# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-01 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_distance', models.IntegerField(default=0)),
                ('tot_time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_tracker.Runner'),
        ),
        migrations.AddField(
            model_name='mile',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_tracker.Run'),
        ),
    ]
