# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mile',
            name='time',
        ),
        migrations.AddField(
            model_name='mile',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mile',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mile',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
