# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('training_tracker', '0003_auto_20170601_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='mile',
            name='mile_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='run',
            name='run_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 3, 13, 59, 44, 796728, tzinfo=utc)),
        ),
    ]
