# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tracker', '0004_auto_20170603_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(),
        ),
    ]
