# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tracker', '0005_auto_20170603_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mile',
            name='mile_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_number',
            field=models.IntegerField(),
        ),
    ]
