# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tracker', '0006_auto_20170603_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='password',
        ),
        migrations.AddField(
            model_name='runner',
            name='age',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='runner',
            name='hours_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='runner',
            name='minutes_goal',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='runner',
            name='seconds_goal',
            field=models.IntegerField(default=0),
        ),
    ]
