# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tracker', '0007_auto_20170603_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mile',
            name='hours',
        ),
        migrations.AlterField(
            model_name='runner',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='runner',
            name='hours_goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='runner',
            name='minutes_goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='runner',
            name='seconds_goal',
            field=models.IntegerField(),
        ),
    ]
