# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_tracker', '0008_auto_20170603_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mile',
            old_name='run',
            new_name='run_id',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='runner',
            new_name='runner_id',
        ),
    ]
