# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_tracker', '0009_auto_20170604_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mile',
            old_name='run_id',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='runner_id',
            new_name='runner',
        ),
    ]
